sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
- lts/*
all_branches: true,
before_script:
- npm install -g @angular/cli
script:
- npm run test:travis
- npm run build:travis
before-deploy:
- cd dist/ngx-round-progress
deploy:
  edge: true
  provider: npm
  email: sliceofbytes@gmail.com
  api_key:
    secure: ZmFeaVjIz5ogHhjt+063tfd6jjbXkXO36ZUnfVYhveany5tAwe5QOlp/QpICyRdgInNtIFVpJHde9MnH81MvqdPfetNA62CIg+CV60O4TXg4Ni3/SZLphYEb3fY664TQMPikP85uAHyiOdR/rQuRxx4cyTJbTDtGRBFlcP+tPq0Fsfurt9lHKs8Imn7+0pufIS2d8Kn7+rMNSbd/eE/+e0U72FvbrHtzSmauqLmUHEzUx969XJxQa3Clk1ia9eBEab6DwNHVzN/np7SsMZMjs8xAXeZTxzxqUqRx/HSBNxgPzldMTGle6rexZI08OfbKeCMKyXwI+SGKYsA6DRuxrtIRD+ksBmfioUMXomCYlEUMh5rs/X9wVOqrwN5mMhk5/4ln5eyljAwg+vvkmFkrO3IgkNVvTf+4SmMjTnLGNPnflNIwqyIWKT9NsTx6Dpwz+EoypPZe6ZGG67n49w9pI8bUIdfwaYQTa3XhbFNUKkn1/jsAkY1SmkidcDF67B8PQCsszjLHhdUKjmLWpmU0RmJDqDh8Tx9/A44RjJKTNQVxHQxL/IkG2Oc+xsY5UrpAvGaBV5fUwaw+HQ93kj/BrmJ2k8gyA33jw2S3SZwuL5WsKWRL9fvxWDJPa7GaJZ3kT6T1BW49Ukvpzdfo4kz40iu32BbMgI6SKQ/kBZ9kVgY=
  on:
    tags: true
    repo: sliceofbytes/ngx-round-progress
  skip_cleanup: true
